; ---------------------------------------------------------------------------
; Object pointers - SK Set 2 (Sprite_ListingK)
;
; Selected by the object loader for the later zone range, including
; MHZ through DDZ/HPZ; see sonic3k.asm loc_1B6A8.  Entries are indexed by
; object ID.  Comments list the hexadecimal object ID, then the original
; decimal index.
;
; SK Set 1 (Sprite_Listing3) reuses many object IDs with different targets.
; ---------------------------------------------------------------------------
	dc.l Obj_Ring				; $00 / 0
	dc.l Obj_Monitor			; $01 / 1
	dc.l Obj_PathSwap			; $02 / 2
	dc.l Obj_MHZTwistedVine			; $03 / 3
	dc.l Obj_CollapsingPlatform		; $04 / 4
	dc.l Obj_AIZLRZEMZRock			; $05 / 5
	dc.l Obj_MHZPulleyLift			; $06 / 6
	dc.l Obj_Spring				; $07 / 7
	dc.l Obj_Spikes				; $08 / 8
	dc.l Obj_MHZCurledVine			; $09 / 9
	dc.l Obj_MHZStickyVine			; $0A / 10
	dc.l Obj_MHZSwingBarHorizontal		; $0B / 11
	dc.l Obj_MHZSwingBarVertical		; $0C / 12
	dc.l Obj_BreakableWall			; $0D / 13
	dc.l Obj_TwistedRamp			; $0E / 14
	dc.l Obj_CollapsingBridge		; $0F / 15
	dc.l Obj_MHZSwingVine			; $10 / 16
	dc.l Obj_MHZMushroomPlatform		; $11 / 17
	dc.l Obj_MHZMushroomParachute		; $12 / 18
	dc.l Obj_MHZMushroomCatapult		; $13 / 19
	dc.l Obj_Updraft			; $14 / 20
	dc.l Obj_LRZCorkscrew			; $15 / 21
	dc.l Obj_LRZWallRide			; $16 / 22
	dc.l Obj_LRZSinkingRock			; $17 / 23
	dc.l Obj_LRZFallingSpike		; $18 / 24
	dc.l Obj_LRZDoor			; $19 / 25
	dc.l Obj_LRZBigDoor			; $1A / 26
	dc.l Obj_LRZFireballLauncher		; $1B / 27
	dc.l Obj_LRZButtonHorizontal		; $1C / 28
	dc.l Obj_LRZShootingTrigger		; $1D / 29
	dc.l Obj_LRZDashElevator		; $1E / 30
	dc.l Obj_LRZLavaFall			; $1F / 31
	dc.l Obj_LRZSwingingSpikeBall		; $20 / 32
	dc.l Obj_LRZSmashingSpikePlatform	; $21 / 33
	dc.l Obj_LRZSpikeBall			; $22 / 34
	dc.l Obj_MHZMushroomCap			; $23 / 35
	dc.l Obj_AutomaticTunnel		; $24 / 36
	dc.l Obj_LRZChainedPlatforms		; $25 / 37
	dc.l Obj_AutoSpin			; $26 / 38
	dc.l Obj_S2LavaMarker			; $27 / 39
	dc.l Obj_InvisibleBlock			; $28 / 40
	dc.l Obj_LRZFlameThrower		; $29 / 41
	dc.l Obj_CorkFloor			; $2A / 42
	dc.l Obj_LRZOrbitingSpikeBallHorizontal	; $2B / 43
	dc.l Obj_LRZOrbitingSpikeBallVertical	; $2C / 44
	dc.l Obj_LRZSolidMovingPlatforms	; $2D / 45
	dc.l Obj_LRZSolidRock			; $2E / 46
	dc.l Obj_StillSprite			; $2F / 47
	dc.l Obj_AnimatedStillSprite		; $30 / 48
	dc.l Obj_LRZCollapsingBridge		; $31 / 49
	dc.l Obj_LRZTurbineSprites		; $32 / 50
	dc.l Obj_Button				; $33 / 51
	dc.l Obj_StarPost			; $34 / 52
	dc.l Obj_AIZForegroundPlant		; $35 / 53
	dc.l Obj_HCZBreakableBar		; $36 / 54
	dc.l Obj_LRZSpikeBallLauncher		; $37 / 55
	dc.l Obj_SOZQuicksand			; $38 / 56
	dc.l Obj_SOZSpawningSandBlocks		; $39 / 57
	dc.l Obj_SOZPathSwap			; $3A / 58
	dc.l Obj_SOZLoopFallthrough		; $3B / 59
	dc.l Obj_Door				; $3C / 60
	dc.l Obj_RetractingSpring		; $3D / 61
	dc.l Obj_SOZPushableRock		; $3E / 62
	dc.l Obj_SOZSpringVine			; $3F / 63
	dc.l Obj_SOZRisingSandWall		; $40 / 64
	dc.l Obj_SOZLightSwitch			; $41 / 65
	dc.l Obj_SOZFloatingPillar		; $42 / 66
	dc.l Obj_SOZSwingingPlatform		; $43 / 67
	dc.l Obj_SOZBreakableSandRock		; $44 / 68
	dc.l Obj_SOZPushSwitch			; $45 / 69
	dc.l Obj_SOZDoor			; $46 / 70
	dc.l Obj_SOZSandCork			; $47 / 71
	dc.l Obj_SOZRapelWire			; $48 / 72
	dc.l Obj_SOZSolidSprites		; $49 / 73
	dc.l Obj_DEZFloatingPlatform		; $4A / 74
	dc.l Obj_DEZTiltingBridge		; $4B / 75
	dc.l Obj_DEZHangCarrier			; $4C / 76
	dc.l Obj_DEZTorpedoLauncher		; $4D / 77
	dc.l Obj_DEZLiftPad			; $4E / 78
	dc.l Obj_DEZStaircase			; $4F / 79
	dc.l Obj_DEZConveyorBelt		; $50 / 80
	dc.l Obj_FloatingPlatform		; $51 / 81
	dc.l Obj_DEZLightning			; $52 / 82
	dc.l Obj_DEZConveyorPad			; $53 / 83
	dc.l Obj_Bubbler			; $54 / 84
	dc.l Obj_DEZEnergyBridge		; $55 / 85
	dc.l Obj_DEZEnergyBridgeCurved		; $56 / 86
	dc.l Obj_DEZTunnelLauncher		; $57 / 87
	dc.l Obj_DEZGravitySwitch		; $58 / 88
	dc.l Obj_DEZTeleporter			; $59 / 89
	dc.l Obj_DEZGravityTube			; $5A / 90
	dc.l Obj_DEZGravitySwap			; $5B / 91
	dc.l Obj_DEZGravityHub			; $5C / 92
	dc.l Obj_DEZRetractingSpring		; $5D / 93
	dc.l Obj_DEZHoverMachine		; $5E / 94
	dc.l Obj_DEZGravityRoom			; $5F / 95
	dc.l Obj_DEZBumperWall			; $60 / 96
	dc.l Obj_DEZGravityPuzzle		; $61 / 97
	dc.l Obj_Ring				; $62 / 98
	dc.l Obj_Ring				; $63 / 99
	dc.l Obj_Ring				; $64 / 100
	dc.l Obj_Ring				; $65 / 101
	dc.l Obj_Ring				; $66 / 102
	dc.l Obj_Ring				; $67 / 103
	dc.l Obj_Ring				; $68 / 104
	dc.l Obj_Ring				; $69 / 105
	dc.l Obj_InvisibleHurtBlockHorizontal	; $6A / 106
	dc.l Obj_InvisibleHurtBlockVertical	; $6B / 107
	dc.l Obj_TensionBridge			; $6C / 108
	dc.l Obj_InvisibleShockBlock		; $6D / 109
	dc.l Obj_InvisibleLavaBlock		; $6E / 110
	dc.l Obj_Ring				; $6F / 111
	dc.l Obj_Ring				; $70 / 112
	dc.l Obj_Ring				; $71 / 113
	dc.l Obj_Ring				; $72 / 114
	dc.l Obj_Ring				; $73 / 115
	dc.l Obj_SSZRetractingSpring		; $74 / 116
	dc.l Obj_SSZSwingingCarrier		; $75 / 117
	dc.l Obj_SSZRotatingPlatform		; $76 / 118
	dc.l Obj_SSZCutsceneBridge		; $77 / 119
	dc.l Obj_FBZDEZPlayerLauncher		; $78 / 120
	dc.l Obj_SSZHPZTeleporter		; $79 / 121
	dc.l Obj_SSZElevatorBar			; $7A / 122
	dc.l Obj_SSZCollapsingBridgeDiagonal	; $7B / 123
	dc.l Obj_SSZCollapsingBridge		; $7C / 124
	dc.l Obj_SSZBouncyCloud			; $7D / 125
	dc.l Obj_SSZCollapsingColumn		; $7E / 126
	dc.l Obj_SSZFloatingPlatform		; $7F / 127
	dc.l Obj_HiddenMonitor			; $80 / 128
	dc.l Obj_EggCapsule			; $81 / 129
	dc.l Obj_CutsceneKnuckles		; $82 / 130
	dc.l Obj_CutsceneButton			; $83 / 131
	dc.l Obj_AIZPlaneIntro			; $84 / 132
	dc.l Obj_SSEntryRing			; $85 / 133
	dc.l Obj_GumballMachine			; $86 / 134
	dc.l Obj_GumballTriangleBumper		; $87 / 135
	dc.l Obj_CNZWaterLevelCorkFloor		; $88 / 136
	dc.l Obj_CNZWaterLevelButton		; $89 / 137
	dc.l Obj_FBZExitHall			; $8A / 138
	dc.l Obj_SpriteMask			; $8B / 139
	dc.l Obj_Madmole			; $8C / 140
	dc.l Obj_Mushmeanie			; $8D / 141
	dc.l Obj_Dragonfly			; $8E / 142
	dc.l Obj_Butterdroid			; $8F / 143
	dc.l Obj_Cluckoid			; $90 / 144
	dc.l Obj_MHZMinibossTree		; $91 / 145
	dc.l Obj_MHZMiniboss			; $92 / 146
	dc.l Obj_MHZEndBoss			; $93 / 147
	dc.l Obj_Skorp				; $94 / 148
	dc.l Obj_Sandworm			; $95 / 149
	dc.l Obj_Rockn				; $96 / 150
	dc.l Obj_SOZMiniboss			; $97 / 151
	dc.l Obj_SOZEndBoss			; $98 / 152
	dc.l Obj_Fireworm			; $99 / 153
	dc.l Obj_Iwamodoki			; $9A / 154
	dc.l Obj_Toxomister			; $9B / 155
	dc.l Obj_LRZRockCrusher			; $9C / 156
	dc.l Obj_LRZMiniboss			; $9D / 157
	dc.l Obj_LRZ3Autoscroll			; $9E / 158
	dc.l Obj_Ring				; $9F / 159
	dc.l Obj_EggRobo			; $A0 / 160
	dc.l Obj_SSZGHZBoss			; $A1 / 161
	dc.l Obj_SSZMTZBoss			; $A2 / 162
	dc.l Obj_SSZEndBoss			; $A3 / 163
	dc.l Obj_Spikebonker			; $A4 / 164
	dc.l Obj_Chainspike			; $A5 / 165
	dc.l Obj_DEZMiniboss			; $A6 / 166
	dc.l Obj_DEZEndBoss			; $A7 / 167
	dc.l Obj_MHZ1CutsceneKnuckles		; $A8 / 168
	dc.l Obj_MHZ1CutsceneButton		; $A9 / 169
	dc.l Obj_SOZGhosts			; $AA / 170
	dc.l Obj_SOZGhostCapsuleLoadArt		; $AB / 171
	dc.l Obj_SOZGhostCapsule		; $AC / 172
	dc.l Obj_LRZ3Platform			; $AD / 173
	dc.l Obj_LRZ2CutsceneKnuckles		; $AE / 174
	dc.l Obj_SSZCutsceneButton		; $AF / 175
	dc.l Obj_HPZMasterEmerald		; $B0 / 176
	dc.l Obj_HPZPaletteControl		; $B1 / 177
	dc.l Obj_KnuxFinalBossCrane		; $B2 / 178
	dc.l Obj_StartNewLevel			; $B3 / 179
	dc.l Obj_HPZSuperEmerald		; $B4 / 180
	dc.l Obj_HPZSSEntryControl		; $B5 / 181
	dc.l Obj_DDZEndBoss			; $B6 / 182
	dc.l Obj_DDZAsteroid			; $B7 / 183
	dc.l Obj_DDZMissile			; $B8 / 184
